import { ServiceItem } from '../types/coolo.types';

export const SERVICES: ServiceItem[] = [
  {
    id: 'srv-repair',
    slug: 'ac-repair',
    name: 'AC Repair',
    shortDescription: 'Comprehensive diagnosis and precision repair for cooling issues, electrical faults, and noise.',
    fullDescription: 'Our technicians diagnose cooling problems, abnormal noises, water leaks, PCB errors, and sensor failures. Receive an upfront diagnostic assessment before any parts are replaced.',
    iconName: 'Wrench',
    startingPrice: 499,
    popular: true,
    features: [
      'Multi-point diagnostic inspection',
      'Accurate problem identification',
      'Genuine replacement parts',
      'Post-repair cooling performance test',
    ],
  },
  {
    id: 'srv-service',
    slug: 'ac-service',
    name: 'AC Service',
    shortDescription: 'Routine servicing, thorough filter cleaning, and coil flush for peak seasonal cooling efficiency.',
    fullDescription: 'Essential maintenance designed to optimize airflow, reduce power consumption, and ensure clean indoor air. Recommended at the start of summer and every 4–6 months.',
    iconName: 'Sparkles',
    startingPrice: 399,
    popular: true,
    features: [
      'High-velocity air filter cleaning',
      'Indoor coil rinse & debris sweep',
      'Outdoor condenser fins wash',
      'Refrigerant operating pressure check',
    ],
  },
  {
    id: 'srv-deep-clean',
    slug: 'ac-deep-cleaning',
    name: 'AC Deep Cleaning',
    shortDescription: 'High-pressure foam jet wash of indoor and outdoor coils to eliminate deep grime, mold, and odor.',
    fullDescription: 'Heavy-duty cleaning for ACs with reduced airflow, foul odor, or mold accumulation. Utilizing jacket protection and specialized foaming agents without splashing walls.',
    iconName: 'Droplets',
    startingPrice: 699,
    popular: true,
    features: [
      'Protective spill jacket covering',
      'Antibacterial foam application',
      'Pressure pump coil wash',
      'Blower wheel & drain pipe declogging',
    ],
  },
  {
    id: 'srv-install',
    slug: 'ac-installation',
    name: 'AC Installation',
    shortDescription: 'Standardized bracket mounting, precision copper piping, vacuuming, and commissioning for new ACs.',
    fullDescription: 'Engineered installation ensuring vibration-free bracket anchoring, zero-leak flare joints, vacuum purging to protect compressor life, and precise airflow positioning.',
    iconName: 'ShieldCheck',
    startingPrice: 1199,
    features: [
      'Precision spirit-level wall mounting',
      'Copper tube flaring & nitrogen test',
      'System vacuuming & moisture purging',
      'Electrical connection & amp load check',
    ],
  },
  {
    id: 'srv-uninstall',
    slug: 'ac-uninstallation',
    name: 'AC Uninstallation',
    shortDescription: 'Safe refrigerant pump-down, controlled electrical disconnection, and protective packaging for relocation.',
    fullDescription: 'Safe uninstallation that locks refrigerant securely in the outdoor condenser unit before disconnecting, avoiding expensive gas loss and tube damage during moves.',
    iconName: 'ArrowDownCircle',
    startingPrice: 649,
    features: [
      'Refrigerant gas pump-down containment',
      'Careful indoor unit unhooking',
      'Outdoor bracket detachment',
      'Protected pipe end sealing',
    ],
  },
  {
    id: 'srv-gas',
    slug: 'ac-gas-charging',
    name: 'AC Gas Charging',
    shortDescription: 'System leak testing, nitrogen pressure check, vacuuming, and precision manufacturer-spec refrigerant refill.',
    fullDescription: 'Complete leak investigation in coils and flare nuts. Once resolved, we perform deep vacuuming and weigh-in exact manufacturer-grade refrigerants (R-32, R-410A, R-22).',
    iconName: 'Gauge',
    startingPrice: 1499,
    features: [
      'Comprehensive leak detection',
      'Vacuum pump evacuation',
      'Weighed gas charging by cylinder scale',
      'Suction pressure & delta-T verification',
    ],
  },
  {
    id: 'srv-amc',
    slug: 'ac-amc',
    name: 'AC AMC Packages',
    shortDescription: 'Annual maintenance contracts providing scheduled preventive tune-ups and priority breakdown response.',
    fullDescription: 'Year-round cooling security with planned seasonal visits, free breakdown callouts, and discounts on parts and gas top-ups. Ideal for busy households and villas.',
    iconName: 'CalendarCheck',
    startingPrice: 1999,
    features: [
      'Scheduled preventive services',
      'Priority emergency call response',
      'Discount on spare components',
      'Annual maintenance health report',
    ],
  },
  {
    id: 'srv-commercial',
    slug: 'commercial-ac',
    name: 'Commercial AC & HVAC',
    shortDescription: 'Specialized cooling maintenance for retail outlets, offices, clinics, server rooms, and commercial spaces.',
    fullDescription: 'Tailored uptime maintenance and servicing for cassette units, VRV/VRF multi-splits, ducted air conditioners, and light commercial cooling equipment.',
    iconName: 'Building2',
    startingPrice: 2499,
    features: [
      'Dedicated commercial service crew',
      'Cassette & ducted unit expertise',
      'Preventive downtime management',
      'Corporate invoicing & GST compliance',
    ],
  },
];
